const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const UPDATE_POLL = "UPDATE_POLL";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const MEMBER_REMOVED = "MEMBER_REMOVED";
const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVE = "CHAT_LEAVE";
const ONLINE_USERS = "ONLINE_USERS";
const CHAT_ONLINE_USERS = "CHAT_ONLINE_USERS";
const REFETCH_MESSAGES = "REFETCH_MESSAGES";
const LAST_CHAT_ONLINE = "LAST_CHAT_ONLINE";
const LAST_ONLINE = "LAST_ONLINE";

export {
  ALERT,
  REFETCH_CHATS,
  UPDATE_POLL,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  MEMBER_REMOVED,
  CHAT_JOINED,
  CHAT_LEAVE,
  ONLINE_USERS,
  CHAT_ONLINE_USERS,
  REFETCH_MESSAGES,
  LAST_CHAT_ONLINE,
  LAST_ONLINE,
};
